import type { Config } from 'tailwindcss'

export default <Partial<Config>>{
  content: [
    './app/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      spacing: {
        'space-md': '1rem',
        'margin-mobile': '1rem',
        'space-2xs': '0.25rem',
        'gutter-sm': '1rem',
        'space-2xl': '3rem',
        'space-xs': '0.5rem',
        'gutter': '1.5rem',
        'space-sm': '0.75rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'margin-new': '2rem',
      },
      // Lưu ý: bản gốc (tailwind.config.js) khai báo `fontFamily` 2 lần trong
      // cùng object `extend`, nên chỉ khối thứ 2 (`sans`) có hiệu lực thật sự —
      // các key headline-*/label-*/body-*/code-sm bên dưới KHÔNG được áp dụng
      // trên site hiện tại (dù các class font-headline-xl... vẫn được dùng
      // trong template, chúng không có style vì Tailwind không sinh ra utility
      // cho các key đã bị ghi đè). Giữ nguyên hành vi này để không đổi giao diện.
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'code-sm': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      colors: {
        'on-secondary-fixed': '#002022',
        'on-primary-fixed': '#001a41',
        'on-secondary-fixed-variant': '#004f53',
        'secondary': '#000000ff',
        'surface-container-high': '#dce9ff',
        'secondary-container': '#61f4fd',
        'surface-tint': '#005bc0',
        'surface': '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'on-surface-variant': '#414754',
        'secondary-fixed': '#6bf6ff',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#3edae3',
        'tertiary-container': '#c44e3e',
        'on-primary': '#ffffff',
        'primary-new': '#0058bc',
        'inverse-primary': '#adc6ff',
        'on-background': '#0b1c30',
        'tertiary-fixed-dim': '#ffb4a8',
        'surface-container': '#e5eeff',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-primary-container': '#fefcff',
        'primary-fixed-dim': '#adc6ff',
        'surface-dim': '#cbdbf5',
        'on-surface': '#0b1c30',
        'error': '#ba1a1a',
        'surface-container-highest': '#d3e4fe',
        'on-tertiary-container': '#fffbff',
        'primary-container': '#0070eb',
        'inverse-surface': '#213145',
        'outline-variant': '#c1c6d6',
        'on-tertiary-fixed': '#410100',
        'on-primary-fixed-variant': '#004493',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'primary-fixed': '#d8e2ff',
        'on-tertiary-fixed-variant': '#862116',
        'outline-new': '#727785',
        'background-new': '#f8f9ff',
        'tertiary': '#a33628',
        'surface-variant': '#d3e4fe',
        'tertiary-fixed': '#ffdad4',
        'on-error-container': '#93000a',
        'on-secondary-container': '#006e73',
        'surface-container-low': '#eff4ff',
        'inverse-on-surface': '#eaf1ff',

        primary: {
          DEFAULT: '#eab308',
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        accent: {
          cyan: '#06b6d4',
          teal: '#0d9488',
          indigo: '#4f46e5',
          purple: '#8b5cf6',
          emerald: '#10b981',
          amber: '#f59e0b',
          rose: '#f43f5e',
        },
      },
    },
  },
  plugins: [],
}
